# Generated by Django 2.2.3 on 2019-07-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
