# Generated by Django 2.2.3 on 2019-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_auto_20190711_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(default='daily', max_length=20),
        ),
    ]
