# Generated by Django 2.2.3 on 2019-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_task_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_to_be_performed_by',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_of_allocation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
